[package]
name = "packet-capture-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
hex = "0.4.3"
log = "0.4.19"
pnet = "0.33.0"
